inherit_from: .rubocop_todo.yml

#inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
AllCops:
  StyleGuideBaseURL: https://rubystyle.guide
  TargetRubyVersion: 2.4
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
    - 'test_matrix.rb'
    - 'lib/puppet-debugger/trollop.rb'
Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/puppet-debugger/monkey_patches.rb'
    - 'lib/puppet/application/debugger.rb'
    - 'spec/spec_helper.rb'
Style/DoubleNegation:
  Exclude:
    - 'lib/puppet-debugger/debugger_code.rb'

Metrics/MethodLength:
  Max: 45
Lint/Debugger:
  Enabled: false
Layout/LineLength:
  Max: 129
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - lib/puppet-debugger/plugin_test_helper.rb 
Metrics/BlockLength:
  Max: 277

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false 
Lint/RaiseException:
  Enabled: false 
Lint/StructNewOverride:
  Enabled: false 
Style/ExponentialNotation:
  Enabled: false 
Style/HashEachMethods:
  Enabled: false 
Style/HashTransformKeys:
  Enabled: false 
Style/HashTransformValues:
  Enabled: false 
Style/RedundantFetchBlock:
  Enabled: false 
Style/RedundantRegexpCharacterClass:
  Enabled: false 
Style/RedundantRegexpEscape:
  Enabled: false 
Style/SlicingWithRange:
  Enabled: false 
Style/AccessorGrouping:
  Enabled: false 
Style/BisectedAttrAccessor:
  Enabled: false 
Style/RedundantAssignment:
  Enabled: false   